package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'First'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("First")) {
    params {
        add {
            checkbox("StartStep", "true", label = "Label Start", description = "Start step one?", display = ParameterDisplay.PROMPT,
                      checked = "true", unchecked = "false")
        }
        add {
            checkbox("WeirdStep", "true",
                      checked = "true", unchecked = "false")
        }
    }

    expectSteps {
        script {
            name = "FirstStep"
            id = "FirstStep"
            scriptContent = """echo "Hello" > /tmp/testFile.txt"""
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()

            conditions {
                equals("StartStep", "true")
            }
        }
    }
}
