package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'First'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("First")) {
    params {
        add {
            checkbox("StartStep", "", label = "Label Start", description = "Start step one?", display = ParameterDisplay.PROMPT,
                      checked = "true", unchecked = "false")
        }
    }
}
